In [1]:
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT0001\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [2]:
df = pd.read_csv(r"C:\Users\KIIT0001\Desktop\resume_matcher\data\Resume.csv")
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [4]:
print(df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

In [5]:
resumes = df['Resume_str']

# view one sample
print(resumes.iloc[0])

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [6]:
text = resumes.iloc[0]
text = re.sub(r'<.*?>', ' ', text)
print(text)

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate

HR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate     Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [7]:
text = text.lower()
print(text)

         hr administrator/marketing associate

hr administrator       summary     dedicated customer service manager with 15+ years of experience in hospitality and customer service management.   respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         highlights         focused on customer satisfaction  team management  marketing savvy  conflict resolution techniques     training and development  skilled multi-tasker  client relations specialist           accomplishments      missouri dot supervisor training certification  certified by ihg in customer loyalty and marketing by segment   hilton worldwide general manager training certification  accomplished trainer for cross server hospitality systems such as    hilton onq  ,   micros    opera pms   , fidelio    opera    reservation system (ors) ,   holidex    completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        experience      hr administrator/marketing associate

hr administrator     dec 2013   to   current      company name   －   city  ,   state     helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  prepares employee separation notices and related documentation  keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  advises management in appropriate resolution of employee relations issues.  administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     marketing associate     designed and created marketing collateral for sales meetings, trade shows and company executives.  managed the in-house advertising program consisting of print and media collateral pieces.  assisted in the complete design and launch of the company's website in 2 months.  created an official company page on facebook to facilitate interaction with customers.  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         advanced medical claims analyst     mar 2012   to   dec 2013      company name   －   city  ,   state     reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  trained to interpret the codes (icd-9, cpt) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         assistant general manager     jun 2010   to   dec 2010      company name   －   city  ,   state     performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  handled daily operations and reported directly to the corporate office.  hired and trained staff on overall objectives and goals with an emphasis on high customer service.  marketing and advertising, working on public relations with the media, government and local businesses and chamber of commerce.         executive support / marketing assistant     jul 2007   to   jun 2010      company name   －   city  ,   state     provided assistance to various department heads - executive, marketing, customer service, human resources.  managed front-end operations to ensure friendly and efficient transactions.  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         reservation & front office manager     jun 2004   to   jul 2007      company name   －   city  ,   state          owner/ partner     dec 2001   to   may 2004      company name   －   city  ,   state          price integrity coordinator     aug 1999   to   dec 2001      company name   －   city  ,   state          education      n/a  ,   business administration   1999     jefferson college   －   city  ,   state       business administration  marketing / advertising         high school diploma  ,   college prep. studies   1998     sainte genevieve senior high   －   city  ,   state       awarded american shrubel leadership scholarship to jefferson college         skills     accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, customer service, data analysis, delivery, documentation, employee relations, financial management, government relations, human resources, insurance, labor relations, layout, marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [8]:
text = re.sub(r'http\S+|www\S+', ' ', text)
text = re.sub(r'\S+@\S+', ' ', text)
print(text)

         hr administrator/marketing associate

hr administrator       summary     dedicated customer service manager with 15+ years of experience in hospitality and customer service management.   respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         highlights         focused on customer satisfaction  team management  marketing savvy  conflict resolution techniques     training and development  skilled multi-tasker  client relations specialist           accomplishments      missouri dot supervisor training certification  certified by ihg in customer loyalty and marketing by segment   hilton worldwide general manager training certification  accomplished trainer for cross server hospitality systems such as    hilton onq  ,   micros    opera pms   , fidelio    opera    reservation system (ors) ,   holidex    completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        experience      hr administrator/marketing associate

hr administrator     dec 2013   to   current      company name   －   city  ,   state     helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  prepares employee separation notices and related documentation  keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  advises management in appropriate resolution of employee relations issues.  administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     marketing associate     designed and created marketing collateral for sales meetings, trade shows and company executives.  managed the in-house advertising program consisting of print and media collateral pieces.  assisted in the complete design and launch of the company's website in 2 months.  created an official company page on facebook to facilitate interaction with customers.  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         advanced medical claims analyst     mar 2012   to   dec 2013      company name   －   city  ,   state     reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  trained to interpret the codes (icd-9, cpt) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         assistant general manager     jun 2010   to   dec 2010      company name   －   city  ,   state     performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  handled daily operations and reported directly to the corporate office.  hired and trained staff on overall objectives and goals with an emphasis on high customer service.  marketing and advertising, working on public relations with the media, government and local businesses and chamber of commerce.         executive support / marketing assistant     jul 2007   to   jun 2010      company name   －   city  ,   state     provided assistance to various department heads - executive, marketing, customer service, human resources.  managed front-end operations to ensure friendly and efficient transactions.  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         reservation & front office manager     jun 2004   to   jul 2007      company name   －   city  ,   state          owner/ partner     dec 2001   to   may 2004      company name   －   city  ,   state          price integrity coordinator     aug 1999   to   dec 2001      company name   －   city  ,   state          education      n/a  ,   business administration   1999     jefferson college   －   city  ,   state       business administration  marketing / advertising         high school diploma  ,   college prep. studies   1998     sainte genevieve senior high   －   city  ,   state       awarded american shrubel leadership scholarship to jefferson college         skills     accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, customer service, data analysis, delivery, documentation, employee relations, financial management, government relations, human resources, insurance, labor relations, layout, marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.

In [9]:
text = text.translate(str.maketrans('', '', string.punctuation))
print(text)

         hr administratormarketing associate

hr administrator       summary     dedicated customer service manager with 15 years of experience in hospitality and customer service management   respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service         highlights         focused on customer satisfaction  team management  marketing savvy  conflict resolution techniques     training and development  skilled multitasker  client relations specialist           accomplishments      missouri dot supervisor training certification  certified by ihg in customer loyalty and marketing by segment   hilton worldwide general manager training certification  accomplished trainer for cross server hospitality systems such as    hilton onq     micros    opera pms    fidelio    opera    reservation system ors    holidex    completed courses and seminars in customer service sales strategies inventory control loss prevention safety time management leadership and performance assessment        experience      hr administratormarketing associate

hr administrator     dec 2013   to   current      company name   －   city     state     helps to develop policies directs and coordinates activities such as employment compensation labor relations benefits training and employee services  prepares employee separation notices and related documentation  keeps records of benefits plans participation such as insurance and pension plan personnel transactions such as hires promotions transfers performance reviews and terminations and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life health dental insurance pension plans vacation sick leave leave of absence and employee assistance     marketing associate     designed and created marketing collateral for sales meetings trade shows and company executives  managed the inhouse advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the companys website in 2 months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies         advanced medical claims analyst     mar 2012   to   dec 2013      company name   －   city     state     reviewed medical bills for the accuracy of the treatments tests and hospital stays prior to sanctioning the claims  trained to interpret the codes icd9 cpt and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills knowledge of medical terminology and procedures statistics billing standards data analysis and laws regarding medical billing         assistant general manager     jun 2010   to   dec 2010      company name   －   city     state     performed duties including but not limited to budgeting and financial management accounting human resources payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation productivity morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising working on public relations with the media government and local businesses and chamber of commerce         executive support  marketing assistant     jul 2007   to   jun 2010      company name   －   city     state     provided assistance to various department heads  executive marketing customer service human resources  managed frontend operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the secondtonone customer service delivery in all interactions with customers and potential clients         reservation  front office manager     jun 2004   to   jul 2007      company name   －   city     state          owner partner     dec 2001   to   may 2004      company name   －   city     state          price integrity coordinator     aug 1999   to   dec 2001      company name   －   city     state          education      na     business administration   1999     jefferson college   －   city     state       business administration  marketing  advertising         high school diploma     college prep studies   1998     sainte genevieve senior high   －   city     state       awarded american shrubel leadership scholarship to jefferson college         skills     accounting ads advertising analytical skills benefits billing budgeting clients customer service data analysis delivery documentation employee relations financial management government relations human resources insurance labor relations layout marketing marketing collateral medical billing medical terminology office organizational payroll performance reviews personnel policies posters presentations public relations purchasing reporting statistics website

In [10]:
text = re.sub(r'\d+', ' ', text)
print(text)

         hr administratormarketing associate

hr administrator       summary     dedicated customer service manager with   years of experience in hospitality and customer service management   respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service         highlights         focused on customer satisfaction  team management  marketing savvy  conflict resolution techniques     training and development  skilled multitasker  client relations specialist           accomplishments      missouri dot supervisor training certification  certified by ihg in customer loyalty and marketing by segment   hilton worldwide general manager training certification  accomplished trainer for cross server hospitality systems such as    hilton onq     micros    opera pms    fidelio    opera    reservation system ors    holidex    completed courses and seminars in customer service sales strategies inventory control loss prevention safety time management leadership and performance assessment        experience      hr administratormarketing associate

hr administrator     dec     to   current      company name   －   city     state     helps to develop policies directs and coordinates activities such as employment compensation labor relations benefits training and employee services  prepares employee separation notices and related documentation  keeps records of benefits plans participation such as insurance and pension plan personnel transactions such as hires promotions transfers performance reviews and terminations and employee statistics for government reporting  advises management in appropriate resolution of employee relations issues  administers benefits programs such as life health dental insurance pension plans vacation sick leave leave of absence and employee assistance     marketing associate     designed and created marketing collateral for sales meetings trade shows and company executives  managed the inhouse advertising program consisting of print and media collateral pieces  assisted in the complete design and launch of the companys website in   months  created an official company page on facebook to facilitate interaction with customers  analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies         advanced medical claims analyst     mar     to   dec        company name   －   city     state     reviewed medical bills for the accuracy of the treatments tests and hospital stays prior to sanctioning the claims  trained to interpret the codes icd  cpt and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers  required to have organizational and analytical skills as well as computer skills knowledge of medical terminology and procedures statistics billing standards data analysis and laws regarding medical billing         assistant general manager     jun     to   dec        company name   －   city     state     performed duties including but not limited to budgeting and financial management accounting human resources payroll and purchasing  established and maintained close working relationships with all departments of the hotel to ensure maximum operation productivity morale and guest service  handled daily operations and reported directly to the corporate office  hired and trained staff on overall objectives and goals with an emphasis on high customer service  marketing and advertising working on public relations with the media government and local businesses and chamber of commerce         executive support  marketing assistant     jul     to   jun        company name   －   city     state     provided assistance to various department heads  executive marketing customer service human resources  managed frontend operations to ensure friendly and efficient transactions  ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies  exemplified the secondtonone customer service delivery in all interactions with customers and potential clients         reservation  front office manager     jun     to   jul        company name   －   city     state          owner partner     dec     to   may        company name   －   city     state          price integrity coordinator     aug     to   dec        company name   －   city     state          education      na     business administration         jefferson college   －   city     state       business administration  marketing  advertising         high school diploma     college prep studies         sainte genevieve senior high   －   city     state       awarded american shrubel leadership scholarship to jefferson college         skills     accounting ads advertising analytical skills benefits billing budgeting clients customer service data analysis delivery documentation employee relations financial management government relations human resources insurance labor relations layout marketing marketing collateral medical billing medical terminology office organizational payroll performance reviews personnel policies posters presentations public relations purchasing reporting statistics website

In [11]:
text = re.sub(r'\s+', ' ', text).strip()
print(text)

hr administratormarketing associate hr administrator summary dedicated customer service manager with years of experience in hospitality and customer service management respected builder and leader of customerfocused teams strives to instill a shared enthusiastic commitment to customer service highlights focused on customer satisfaction team management marketing savvy conflict resolution techniques training and development skilled multitasker client relations specialist accomplishments missouri dot supervisor training certification certified by ihg in customer loyalty and marketing by segment hilton worldwide general manager training certification accomplished trainer for cross server hospitality systems such as hilton onq micros opera pms fidelio opera reservation system ors holidex completed courses and seminars in customer service sales strategies inventory control loss prevention safety time management leadership and performance assessment experience hr administratormarketing associate hr administrator dec to current company name － city state helps to develop policies directs and coordinates activities such as employment compensation labor relations benefits training and employee services prepares employee separation notices and related documentation keeps records of benefits plans participation such as insurance and pension plan personnel transactions such as hires promotions transfers performance reviews and terminations and employee statistics for government reporting advises management in appropriate resolution of employee relations issues administers benefits programs such as life health dental insurance pension plans vacation sick leave leave of absence and employee assistance marketing associate designed and created marketing collateral for sales meetings trade shows and company executives managed the inhouse advertising program consisting of print and media collateral pieces assisted in the complete design and launch of the companys website in months created an official company page on facebook to facilitate interaction with customers analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies advanced medical claims analyst mar to dec company name － city state reviewed medical bills for the accuracy of the treatments tests and hospital stays prior to sanctioning the claims trained to interpret the codes icd cpt and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers required to have organizational and analytical skills as well as computer skills knowledge of medical terminology and procedures statistics billing standards data analysis and laws regarding medical billing assistant general manager jun to dec company name － city state performed duties including but not limited to budgeting and financial management accounting human resources payroll and purchasing established and maintained close working relationships with all departments of the hotel to ensure maximum operation productivity morale and guest service handled daily operations and reported directly to the corporate office hired and trained staff on overall objectives and goals with an emphasis on high customer service marketing and advertising working on public relations with the media government and local businesses and chamber of commerce executive support marketing assistant jul to jun company name － city state provided assistance to various department heads executive marketing customer service human resources managed frontend operations to ensure friendly and efficient transactions ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies exemplified the secondtonone customer service delivery in all interactions with customers and potential clients reservation front office manager jun to jul company name － city state owner partner dec to may company name － city state price integrity coordinator aug to dec company name － city state education na business administration jefferson college － city state business administration marketing advertising high school diploma college prep studies sainte genevieve senior high － city state awarded american shrubel leadership scholarship to jefferson college skills accounting ads advertising analytical skills benefits billing budgeting clients customer service data analysis delivery documentation employee relations financial management government relations human resources insurance labor relations layout marketing marketing collateral medical billing medical terminology office organizational payroll performance reviews personnel policies posters presentations public relations purchasing reporting statistics website

In [12]:
stop_words = set(stopwords.words('english'))

words = text.split()
words = [w for w in words if w not in stop_words]

clean_text = " ".join(words)
print(clean_text)

hr administratormarketing associate hr administrator summary dedicated customer service manager years experience hospitality customer service management respected builder leader customerfocused teams strives instill shared enthusiastic commitment customer service highlights focused customer satisfaction team management marketing savvy conflict resolution techniques training development skilled multitasker client relations specialist accomplishments missouri dot supervisor training certification certified ihg customer loyalty marketing segment hilton worldwide general manager training certification accomplished trainer cross server hospitality systems hilton onq micros opera pms fidelio opera reservation system ors holidex completed courses seminars customer service sales strategies inventory control loss prevention safety time management leadership performance assessment experience hr administratormarketing associate hr administrator dec current company name － city state helps develop policies directs coordinates activities employment compensation labor relations benefits training employee services prepares employee separation notices related documentation keeps records benefits plans participation insurance pension plan personnel transactions hires promotions transfers performance reviews terminations employee statistics government reporting advises management appropriate resolution employee relations issues administers benefits programs life health dental insurance pension plans vacation sick leave leave absence employee assistance marketing associate designed created marketing collateral sales meetings trade shows company executives managed inhouse advertising program consisting print media collateral pieces assisted complete design launch companys website months created official company page facebook facilitate interaction customers analyzed ratings programming features competitors evaluate effectiveness marketing strategies advanced medical claims analyst mar dec company name － city state reviewed medical bills accuracy treatments tests hospital stays prior sanctioning claims trained interpret codes icd cpt terminology commonly used medical billing fully understand paperwork submitted healthcare providers required organizational analytical skills well computer skills knowledge medical terminology procedures statistics billing standards data analysis laws regarding medical billing assistant general manager jun dec company name － city state performed duties including limited budgeting financial management accounting human resources payroll purchasing established maintained close working relationships departments hotel ensure maximum operation productivity morale guest service handled daily operations reported directly corporate office hired trained staff overall objectives goals emphasis high customer service marketing advertising working public relations media government local businesses chamber commerce executive support marketing assistant jul jun company name － city state provided assistance various department heads executive marketing customer service human resources managed frontend operations ensure friendly efficient transactions ensured swift resolution customer issues preserve customer loyalty complying company policies exemplified secondtonone customer service delivery interactions customers potential clients reservation front office manager jun jul company name － city state owner partner dec may company name － city state price integrity coordinator aug dec company name － city state education na business administration jefferson college － city state business administration marketing advertising high school diploma college prep studies sainte genevieve senior high － city state awarded american shrubel leadership scholarship jefferson college skills accounting ads advertising analytical skills benefits billing budgeting clients customer service data analysis delivery documentation employee relations financial management government relations human resources insurance labor relations layout marketing marketing collateral medical billing medical terminology office organizational payroll performance reviews personnel policies posters presentations public relations purchasing reporting statistics website

In [13]:
stop_words = set(stopwords.words('english'))

def clean_resume(text):
    # remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)
    
    # lowercase
    text = text.lower()
    
    # remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)
    
    # remove emails
    text = re.sub(r'\S+@\S+', ' ', text)
    
    # remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # remove numbers
    text = re.sub(r'\d+', ' ', text)
    
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # remove stopwords
    words = text.split()
    words = [w for w in words if w not in stop_words]
    
    return " ".join(words)

In [14]:
df['cleaned_resume'] = df['Resume_str'].apply(clean_resume)

df[['Resume_str', 'cleaned_resume']].head()

,Resume_str,cleaned_resume
0,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,hr administratormarketing associate hr adminis...
1,"HR SPECIALIST, US HR OPERATIONS ...",hr specialist us hr operations summary versati...
2,HR DIRECTOR Summary Over 2...,hr director summary years experience recruitin...
3,HR SPECIALIST Summary Dedica...,hr specialist summary dedicated driven dynamic...
4,HR MANAGER Skill Highlights ...,hr manager skill highlights hr skills hr depar...

In [16]:
df.to_csv(r"C:\Users\KIIT0001\Desktop\resume_matcher\data\cleaned_resume.csv", index=False)